### ISSUE TITLE
openapi support?

### ISSUE THREAD

**Issue by bsypniewski** [up9inc/mockintosh#125]
Hi. I was just wondering if there is plan for openapi support. It would be great if you could just use openapi3.x specification and based on that create mocked service with endpoint responsing according to what is specified in openapi yaml file.

**Comment by undera** [comment]
Hi,
Yes, it is planned. Proof: https://github.com/up9inc/mockintosh/blob/main/docs/Changelog.md mentions it in Roadmap section.

**Comment by undera** [comment]
This has been implemented and will be part of the next release. Meanwhile, you can try it by installing from GitHub source, or via `unstable` Docker image tag.

**Comment by rngtng** [comment]
I've a follow up question: according to https://openapi.tools/ OAS 3.1 is supported, although the conversion fails for me with (docker image tag `unstable`)

```
Failed validating 'pattern' in schema['properties']['openapi']:
    {'pattern': '^3\\.0\\.\\d(-.+)?$', 'type': 'string'}

On instance['openapi']:
    '3.1.0'
```

So am I right to assume that only versions <= 3.0.3 are supported yet? Or am I missing something? Thx
