### ISSUE TITLE
Mocking https dependencies?

### ISSUE THREAD

**Issue by ksudhir007** [up9inc/mockintosh#140]
I haven't found an answer to this question in the docs or the webinar. Please point me to the docs/examples if any.

If a service talks to a third party dependency using HTTPS and I would like to use mockintosh to mock the responses from this third party dependency, how would I do this when I want to build templates based on unhandled requests instead of carefully crafting them manually?

**Comment by undera** [comment]
You should use `fallbackTo` option: https://mockintosh.io/Configuring.html#fallback-to
And also enable the Management API.

Then, all your requests to mocked service will be passed to real service, and "Unhandled requests" tab will fill up with proposed configuration for it.

**Comment by ksudhir007** [comment]
Thank you @undera for looking into this. fallbackTo is a great option for recording requests but my question was more specific to HTTPS. 

A ——> B

A———> mockintosh ———> B

TLS/SSL guarantees that there are no eavesdropping by the in-between proxy (mockintosh) in this case. How is mockintosh reading the requests in HTTPS connection in this scenario?

**Comment by undera** [comment]
To build the configuration, Mockintosh needs to look at the traffic. If you forbid that, how can Mockintosh give you "templates based on unhandled requests"?

You can have "A --> mockintosh" chain also covered with SSL by specifying `ssl: true` option for service. If you are worried about what mockintosh does with traffic inside, you can look at its source code and make sure it is not sent anywhere.

Also make sure that the place where Mockintosh runs is a safe environment, eg your laptop.

**Comment by undera** [comment]
If no further questions - I'm closing this issue. Feel free to reopen it if needed.
