### ISSUE TITLE
Management UI: Load configuration

### ISSUE THREAD

**Issue by wenyuansong** [up9inc/mockintosh#156]
Hi, 

Thanks for the awesome tool!   

I have a minor issue regarding loading configuration file.
What current "Load" button on management UI does is actually "reset" config in memory instead of reloading configuration file from disk. 
What I'm looking for is a button to reload file from disk so that don't need to restart mockintosh every time the config file is updated.
Could you please consider "fixing" the load button or adding a new button?  Thank you!

**Comment by undera** [comment]
Hello,
The current way to reload the configuration from disk is by sending `SIGHUP` signal to Mockintosh process.
Current implementation does not allow full reload via web UI.

The "Load" should probably be gone from UI, to avoid confusion...

**Comment by wenyuansong** [comment]
thanks @undera for your quick response. 
I understand that reloading config file needs to recreate httpServer which will kill UI.  yes, not worth to "fix" it.
