### ISSUE TITLE
Mockintosh doesn't run on windows server

### ISSUE THREAD

**Issue by wenyuansong** [up9inc/mockintosh#158]
Hi, 

I tried to deploy mockintosh onto our test windows server 2012 to replace other mocking tools but it threw the following error. 
Commented out SIGHUP lines in __init__.py and it works. Wondering if should make the SIGHUP handling optional or configurable. 

C:\Users\ryan.song\Desktop>mockintosh mock.yaml
[2021-12-07 22:24:32,701 root INFO] Mockintosh v0.13.17 is starting...
[2021-12-07 22:24:32,701 root INFO] Reading configuration file from path: mock.y
aml
[2021-12-07 22:24:32,717 root INFO] Configuration file is a valid YAML file.
[2021-12-07 22:24:32,717 root INFO] Configuration file is valid according to the
 JSON schema.
Traceback (most recent call last):
  File "runpy.py", line 194, in _run_module_as_main
  File "runpy.py", line 87, in _run_code
  File "C:\Users\ryan.song\AppData\Local\Mockintosh\bin\mockintosh.exe\__main__.
py", line 18, in <module>
  File "C:\Users\ryan.song\AppData\Local\Mockintosh\pkgs\mockintosh\__init__.py"
, line 288, in initiate
    while run(source, debug=debug_mode, interceptors=interceptors, address=addre
ss,
  File "C:\Users\ryan.song\AppData\Local\Mockintosh\pkgs\mockintosh\__init__.py"
, line 115, in run
    prev_handler = signal.getsignal(signal.SIGHUP)
AttributeError: module 'signal' has no attribute 'SIGHUP'

Host Name:                 WIN-PMVEPODMBCO
OS Name:                   Microsoft Windows Server 2012 R2 Standard
OS Version:                6.3.9600 N/A Build 9600
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Server
OS Build Type:             Multiprocessor Free
Registered Owner:          EC2
Registered Organization:   Amazon.com
Original Install Date:     8/30/2019, 7:13:39 PM
System Boot Time:          11/13/2021, 5:02:33 PM
System Manufacturer:       Xen
System Model:              HVM domU
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 79 Stepping 1 GenuineInt
el ~2300 Mhz
BIOS Version:              Xen 4.2.amazon, 8/24/2006
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC) Coordinated Universal Time
Total Physical Memory:     8,192 MB
Available Physical Memory: 2,767 MB
Virtual Memory: Max Size:  16,384 MB
Virtual Memory: Available: 10,039 MB
Virtual Memory: In Use:    6,345 MB
Page File Location(s):     C:\pagefile.sys

**Comment by undera** [comment]
Sorry for breaking it. I see how to fix it. 
Until the fix, just use older release of Mockintosh, the `0.13.16`: https://github.com/up9inc/mockintosh/releases/tag/0.13.16

**Comment by wenyuansong** [comment]
thank you @undera

**Comment by undera** [comment]
The fix has been committed. Will be part of the nearest release
