### ISSUE TITLE
Add Faker Localization Support

### ISSUE THREAD

**Issue by Plaw-Ster** [up9inc/mockintosh#160]
Hi,

Can you add localization support for templating with Faker, define by an environment variable ?
I didn't see how to change it on the documentation of Mockintosh and I saw that Faker is init by default.

Here my two cents for this issue, I tried it locally and change the locale by defining the environment variable in my container.
Works well, give it a try :)

```
diff --git a/mockintosh/templating.py b/mockintosh/templating.py
index 22c2c2d..2aa6631 100644
--- a/mockintosh/templating.py
+++ b/mockintosh/templating.py
@@ -26,7 +26,7 @@ if not cov_no_import:
     import queue
 
 compiler = Compiler()
-faker = Faker()
+faker = Faker(environ.get('MOCKINTOSH_FAKER_LOCALE','en_US'))
 hbs_faker = HbsFaker()
 
 debug_mode = environ.get('MOCKINTOSH_DEBUG', False)
```

Thanks for this wonderful app :+1:

**Comment by undera** [comment]
Thanks for your suggestion!
I have committed the corresponding change into `main` branch.
