### ISSUE TITLE
Encode Base64 in response templating

### ISSUE THREAD

**Issue by sergeidyga** [up9inc/mockintosh#162]
Hi 👋 

Is it possible to base64 encode via response templates?
Something like:
```yaml
body: "{{ 'some_token' | b64encode }}"
```

This can slightly help in mocks maintenance.

**Comment by undera** [comment]
If you use Jinja2 as templating language, that would work exactly like you wrote it

**Comment by sergeidyga** [comment]
Thank you! I hadn't notice ability to [switch templatingEngine](https://mockintosh.io/Configuring.html#advanced-templating-with-jinja2). Now everything is clear.
