### ISSUE TITLE
Traffic Management Instructions not clear

### ISSUE THREAD

**Issue by QAInsights** [up9inc/mockintosh#70]
Traffic Log enable options in the [document ](https://mockintosh.io/Management.html)is not clear. Please let me know how do we enable the traffic log. 

![image](https://user-images.githubusercontent.com/2826376/111019812-6b75c200-83b9-11eb-90fe-7dd879a50e21.png)

**Comment by undera** [comment]
Traffic log is new feature that will be available in the upcoming version.

**Comment by undera** [comment]
You can preview this feature by installing Mockintosh from source code
