### ISSUE TITLE
Traffic Log keeps sending DELETE calls

### ISSUE THREAD

**Issue by QAInsights** [up9inc/mockintosh#73]
I enabled Traffic Log in the management UI. When I observed in the Network tab from Developer Tools, it keeps sending DELETE calls for every second. Is this expected behavior?

![image](https://user-images.githubusercontent.com/2826376/111043757-2fd00c00-843c-11eb-95e0-6d3d94117d08.png)

**Comment by undera** [comment]
Yes, it is expected for UI to do so

сб, 13 мар. 2021 г., 23:39 NaveenKumar Namachivayam ⚡ <
***@***.***>:

**Comment by QAInsights** [comment]
Thank you. I am closing this. Can we get this documented somewhere @undera ?
